# Generated by Django 2.2.4 on 2021-05-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0003_auto_20210530_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='log_app.Users'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
