# Generated by Django 2.2.4 on 2021-05-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_exam_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='dashboard_exam_app.Users'),
        ),
    ]
